# Generated by Django 3.2.4 on 2021-06-03 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='skill',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
