# Generated by Django 3.2.4 on 2021-06-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='skill.png', null=True, upload_to=''),
        ),
    ]
